---
- name: check cisco ios running version
  hosts: all
  connection: local
  
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: ec2-user
      ssh_keyfile: /root/lrich.pem
      

  tasks:
    - name: run show version
      ios_command:
        commands: show version
        provider: "{{ cli }}"
      register: shver
      
    - name: collect and validate version
      ios_facts:
        gather_subset: all
        provider: "{{ cli }}"
      
