---
- name: check cisco ios running version
  hosts: all
  connection: local
  
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: ec2-user
      ssh_keyfile: /root/lrich.pem
      transport: cli

  tasks:
    - name: Use the raw module
      raw: "show version"
      
    - name: collect and validate version
      ios_facts:
        gather_subset: all
        provider: "{{ cli }}"
      
