---
- name: check cisco ios running version
  hosts: all
  connection: local
  
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      transport: cli

  tasks:
    - name: collect and validate version
      ios_facts:
        gather_subset: all
        provider: "{{ cli }}"
      
