---
- name: check cisco ios running version
  hosts: all
  
  vars:
    cli:
      host: "{{ inventory_hostname }}"
      transport: smart

  tasks:
    - name: collect and validate version
      ios_command:
        commands: show version
        provider: "{{ cli }}"
      register: shver

    - debug: msg="{{ shver.stdout }}"
